development:
  adapter: postgresql
  encoding: unicode
  database: musicapp_development
  host: localhost
  pool: 5
  username: postgresuser
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: musicapp_test
  pool: 5
  username: postgresuser
  password: postgres